// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhJ07Xz5Q-N3Ji3ihQ6KFBs7lI2Xjxynw',
    appId: '1:903359170565:web:dea0551c3c15d11288746c',
    messagingSenderId: '903359170565',
    projectId: 'shopapp-d2025',
    authDomain: 'shopapp-d2025.firebaseapp.com',
    databaseURL: 'https://shopapp-d2025-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-d2025.appspot.com',
    measurementId: 'G-4FLTJ0ER3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1MqGVaTHpVo3lOD7VSwDwN4PulFUVR2I',
    appId: '1:903359170565:android:5c9f289c8e20dea488746c',
    messagingSenderId: '903359170565',
    projectId: 'shopapp-d2025',
    databaseURL: 'https://shopapp-d2025-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-d2025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKOPMjyVgCvpZwGBWzRJ8xvZjxk3lpXDo',
    appId: '1:903359170565:ios:0f3c38683936dbcd88746c',
    messagingSenderId: '903359170565',
    projectId: 'shopapp-d2025',
    databaseURL: 'https://shopapp-d2025-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-d2025.appspot.com',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKOPMjyVgCvpZwGBWzRJ8xvZjxk3lpXDo',
    appId: '1:903359170565:ios:0f3c38683936dbcd88746c',
    messagingSenderId: '903359170565',
    projectId: 'shopapp-d2025',
    databaseURL: 'https://shopapp-d2025-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-d2025.appspot.com',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhJ07Xz5Q-N3Ji3ihQ6KFBs7lI2Xjxynw',
    appId: '1:903359170565:web:fd67053e1eeff6a588746c',
    messagingSenderId: '903359170565',
    projectId: 'shopapp-d2025',
    authDomain: 'shopapp-d2025.firebaseapp.com',
    databaseURL: 'https://shopapp-d2025-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-d2025.appspot.com',
    measurementId: 'G-7Z35DZQNMQq',
  );
}
